### ISSUE TITLE
smartblog tab not showing in dashboard in prestashop 1.7.5

### ISSUE THREAD

**Issue by elisaBa** [smartdatasoft/smartblog#108]
smartblog tab not showing in dashboard on prestashop 1.7.5

Installed all the components but the Blog tab has not appeared in the dashboard. Have looked for it in all menus and in front end (store) and is absent as well aka not showing any trace. How can I use the module if don't have an admin panel to even write the posts? Any known solution for this? 
thank you in advance. 

![download](https://user-images.githubusercontent.com/46333647/50620048-d851bf80-0f05-11e9-9378-0348933e5887.png)

**Comment by dbartelmus** [comment]
Same problem. No answer but someone in forum (official topic @ Prestahop forum) touched this issue, still no solved (I guess?).

**Comment by Enumbin** [comment]
I did not find the issue. For further issue please open support ticket at https://support.classydevs.com/support/

**Comment by MchvAdams** [comment]
I don't what is happening here. I'm excited to be a part of this. I'm a new member here and want to learn different stuff on this platform.  Currently, I'm working as a fashion designer and want to pursue more in this field and domains related to fashion. I'm searching for different designs for [bomber jackets in affordable prices](https://genuineleatherjackets.com/category/womens/best-bomber-jackets/) so that people will like them and buy them too, in affordable prices.
